project:
  name: ceoa
  regions:
    - us-east-1
tests:
  lesson1-automate:
    parameters:
      CodeCommitS3Bucket: ceoa-workshop
      CodeCommitS3Key: ceoa-1-examples.zip
    template: ./lesson1-automate/ceoa-1-cfn.yml
