project:
  name: ceoa
  regions:
    - us-east-1
    - us-east-2
tests:
  lesson1-automate:
    template: ./lesson1-automate/ceoa-1-cfn.yml
  lesson4-transit:
    parameters:
      CodeCommitS3Bucket: ceoa-workshop-$(aws sts get-caller-identity --output text --query 'Account') 
      CodeCommitS3Key: ceoa-4-examples.zip
      SiteBucketName: www.encryptaws.com
    template: ./lesson4-transit/tls-pipeline.yml
  lesson5-rest:
    parameters:
      AvailabilityZones: '$[taskcat_genaz_1]'
    template: ./lesson5-rest/ceoa-5-ebs.yml
