project:
  name: ceoa
  regions:
    - us-east-1
    - us-east-2
tests:
  # taskcat-pipeline:
  #   template: ./pipeline-taskcat.yml
  lesson1-automate:
    template: ./lesson1-automate/ceoa-1-cfn.yml
  lesson5-s3:
    template: ./lesson5-rest/ceoa-5-s3.yml
  lesson5-ebs:
    parameters:
      AvailabilityZones: '$[taskcat_genaz_1]'
    template: ./lesson5-rest/ceoa-5-ebs.yml
  lesson5-ddb:
    template: ./lesson5-rest/ceoa-5-ddb.yml