project:
  name: ceoa
  regions:
    - us-east-1
    # - us-east-2
tests:
  # l0-test-ssm-param:
  #   template: ./lesson0-setup/test-ssm-param.yml
  # lesson1-automate:
  #   template: ./lesson1-automate/ceoa-1-cfn.yml
  # lesson1-pipeline:
  #   parameters:
  #     CodeCommitS3Bucket: ceoa-workshop
  #     CodeCommitS3Key: ceoa-1-examples.zip
  #   template: ./lesson1-automate/ceoa-1-pipeline.yml
  # l2:
  #   template: ./lesson2-manage/ceoa-2-kms.yml
  # l4:
  #   parameters:
  #     CodeCommitS3Bucket: ceoa-workshop
  #     CodeCommitS3Key: ceoa-4-examples.zip
  #   template: ./lesson4-transit/ceoa-4-pipeline.yml
  # l5-rest-ebs:
  #   parameters:
  #     AvailabilityZones: '$[taskcat_genaz_1]'
  #   template: ./lesson5-rest/ceoa-5-ebs.yml
  # l5-rest-ddb:
  #   template: ./lesson5-rest/ceoa-5-ddb.yml
  # l5-rest-s3:
  #   template: ./lesson5-rest/ceoa-5-s3.yml
  # l5-rest-kms:
  #   template: ./lesson5-rest/ceoa-5-kms.yml
  # l7-log-cloudtrail:
  #   template: ./lesson7-log/ceoa-7-cloudtrail.yml
  l8:
    parameters:
      S3ComplianceResourceId: ceoa-82-s3-test
      CodeCommitS3Bucket: ceoa-workshop
      CodeCommitS3Key: ceoa-8-examples.zip
    template: ./lesson8-continuous/ceoa-8-pipeline.yml