version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - python --version
  build:
    commands:
      - echo MUST MANUALLY CREATE ceoa-workshop-ACCOUNTID S3 BUCKET
      - echo In buildspec-setup.yml Build started on `date`
      - aws s3 sync . s3://ceoa-workshop-$(aws sts get-caller-identity --output text --query 'Account')
      - cd lesson4-transit
      - zip ceoa-4-examples.zip *.*
      - aws s3 sync . s3://ceoa-workshop-$(aws sts get-caller-identity --output text --query 'Account')
      - cd ../lesson2-manage
      - zip ceoa-2-examples.zip *.*
      - aws s3 sync . s3://ceoa-workshop-$(aws sts get-caller-identity --output text --query 'Account')
  post_build:
    commands:
      - echo In buildspec-setup.yml Build completed on `date`
artifacts:
  files:
    - '**/*'
