version: 0.2
phases:
  build:
    commands:
      - echo Build started on `date`
      - pip3 install taskcat --user
      - taskcat test run
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
