version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  build:
    commands:
      - echo Build started on `date`
      - python --version
      - 'curl -O https://bootstrap.pypa.io/get-pip.py'
      - python3 get-pip.py
      - pip install --upgrade pip
      - pip3 install taskcat
      - taskcat test run -n
      - aws s3api list-buckets --query 'Buckets[?starts_with(Name, `www.encryptaws.com`) == `true`].[Name]' --output text | xargs -I {} aws s3 rb s3://{} --force
  post_build:
    commands:
      - echo Build completed on `date`
      - aws s3api list-buckets --query 'Buckets[?starts_with(Name, `www.encryptaws.com`) == `true`].[Name]' --output text | xargs -I {} aws s3 rb s3://{} --force
artifacts:
  files:
    - '**/*'
