---
AWSTemplateFormatVersion: '2010-09-09'
Description: Test Import Value from Export Value
Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::ImportValue: 'PrivateSubnet1'
      
      
      