  StaticWebBucketPolicy: 
    Type: "AWS::S3::BucketPolicy"
    Properties: 
      Bucket: 
        Fn::ImportValue: "us-east-1-ceoa-tls-pipeline-static-web-buckets"
      PolicyDocument: 
        Statement: 
          - Action: 
              - "s3:*"
            Effect: "Allow"
            Resource: !Sub "arn:aws:s3:::www.encryptaws.com/*"
            Principal: 
              AWS: !Sub "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CloudFrontOriginAccessIdentity}"
